// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/native_core.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class NativeCoreBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeCoreBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeCoreBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int cmd(int argc, ffi.Pointer<ffi.Pointer<ffi.Char>> argv) {
    return _cmd(argc, argv);
  }

  late final _cmdPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Pointer<ffi.Char>>)
    >
  >('cmd');
  late final _cmd =
      _cmdPtr
          .asFunction<int Function(int, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int server() {
    return _server();
  }

  late final _serverPtr = _lookup<ffi.NativeFunction<ffi.Int Function()>>(
    'server',
  );
  late final _server = _serverPtr.asFunction<int Function()>();
}
