// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/native_core.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class NativeCoreBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeCoreBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeCoreBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int hdcCmd(int argc, ffi.Pointer<ffi.Pointer<ffi.Char>> args) {
    return _hdcCmd(argc, args);
  }

  late final _hdcCmdPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Pointer<ffi.Char>>)
    >
  >('hdcCmd');
  late final _hdcCmd =
      _hdcCmdPtr
          .asFunction<int Function(int, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  void hdcServer() {
    return _hdcServer();
  }

  late final _hdcServerPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>(
    'hdcServer',
  );
  late final _hdcServer = _hdcServerPtr.asFunction<void Function()>();

  int signCmd(int argc, ffi.Pointer<ffi.Pointer<ffi.Char>> args) {
    return _signCmd(argc, args);
  }

  late final _signCmdPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Pointer<ffi.Char>>)
    >
  >('signCmd');
  late final _signCmd =
      _signCmdPtr
          .asFunction<int Function(int, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  ffi.Pointer<ffi.Char> uzip(
    ffi.Pointer<ffi.Char> source,
    ffi.Pointer<ffi.Char> fileName,
    ffi.Pointer<ffi.Char> destination,
  ) {
    return _uzip(source, fileName, destination);
  }

  late final _uzipPtr = _lookup<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Char> Function(
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
      )
    >
  >('uzip');
  late final _uzip =
      _uzipPtr
          .asFunction<
            ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();
}
